// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Solar.Infrastructure.Context;

#nullable disable

namespace Solar.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260213174152_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Solar.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("Solar.Domain.Entities.Procedimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Concluido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("Concluido");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataConclusao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("Descricao");

                    b.Property<Guid>("ProjetoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.ToTable("Procedimentos", (string)null);
                });

            modelBuilder.Entity("Solar.Domain.Entities.Projeto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DataFinal")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataFinal");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataInicio");

                    b.Property<Guid>("LiderTecnicoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Localizacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nome");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ValorTotal");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("LiderTecnicoId");

                    b.ToTable("Projetos", (string)null);
                });

            modelBuilder.Entity("Solar.Domain.Entities.Tecnico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Cargo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("Tecnicos", (string)null);
                });

            modelBuilder.Entity("TecnicoEquipeProjeto", b =>
                {
                    b.Property<Guid>("ProjetoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TecnicoId")
                        .HasColumnType("char(36)");

                    b.HasKey("ProjetoId", "TecnicoId");

                    b.HasIndex("TecnicoId");

                    b.ToTable("TecnicoEquipeProjeto");
                });

            modelBuilder.Entity("Solar.Domain.Entities.Procedimento", b =>
                {
                    b.HasOne("Solar.Domain.Entities.Projeto", "Projeto")
                        .WithMany("Procedimentos")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("Solar.Domain.Entities.Projeto", b =>
                {
                    b.HasOne("Solar.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Projetos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Solar.Domain.Entities.Tecnico", "LiderTecnico")
                        .WithMany("ProjetosLider")
                        .HasForeignKey("LiderTecnicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("LiderTecnico");
                });

            modelBuilder.Entity("TecnicoEquipeProjeto", b =>
                {
                    b.HasOne("Solar.Domain.Entities.Projeto", null)
                        .WithMany()
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Solar.Domain.Entities.Tecnico", null)
                        .WithMany()
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Solar.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Projetos");
                });

            modelBuilder.Entity("Solar.Domain.Entities.Projeto", b =>
                {
                    b.Navigation("Procedimentos");
                });

            modelBuilder.Entity("Solar.Domain.Entities.Tecnico", b =>
                {
                    b.Navigation("ProjetosLider");
                });
#pragma warning restore 612, 618
        }
    }
}
